[package]
name = "anstyle-migration-tool"
version = "0.20.3"
edition = "2021"
description = "A tool to migrate anstyle usage in Rust projects"
license = "MIT"
repository = "https://github.com/crate-ci/cargo-release"

[dependencies]
regex = "1.0"
